name: Update GitHub Pages
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - name: Sync
      run: uv sync
    - name: Build docs
      run: uv run make -C docs html
    - uses: actions/upload-pages-artifact@v5
      with:
        path: ./docs/build/html/

  update-gh-pages:
    name: Update gh-pages
    environment:
      name: github-pages
    needs: [build-docs]
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v5

